[
  {
    id: "41",
    title: "NIGHT SUIT",
    description: "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
    price: 55,
    discountPercentage: 15.05,
    rating: 4.65,
    stock: 21,
    brand: "RED MICKY MOUSE..",
    category: "womens-dresses",
    thumbnail: "https://cdn.dummyjson.com/product-images/41/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/41/1.jpg",
      "https://cdn.dummyjson.com/product-images/41/2.webp",
      "https://cdn.dummyjson.com/product-images/41/3.jpg",
      "https://cdn.dummyjson.com/product-images/41/4.jpg",
      "https://cdn.dummyjson.com/product-images/41/thumbnail.webp",
    ],
  },
  {
    id: "42",
    title: "Stiched Kurta plus trouser",
    description:
      "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
    price: 80,
    discountPercentage: 15.37,
    rating: 4.05,
    stock: 148,
    brand: "Digital Printed",
    category: "womens-dresses",
    thumbnail: "https://cdn.dummyjson.com/product-images/42/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/42/1.png",
      "https://cdn.dummyjson.com/product-images/42/2.png",
      "https://cdn.dummyjson.com/product-images/42/3.png",
      "https://cdn.dummyjson.com/product-images/42/4.jpg",
      "https://cdn.dummyjson.com/product-images/42/thumbnail.jpg",
    ],
  },
  {
    id: "43",
    title: "frock gold printed",
    description:
      "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
    price: 600,
    discountPercentage: 15.55,
    rating: 4.31,
    stock: 150,
    brand: "Ghazi Fabric",
    category: "womens-dresses",
    thumbnail: "https://cdn.dummyjson.com/product-images/43/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/43/1.jpg",
      "https://cdn.dummyjson.com/product-images/43/2.jpg",
      "https://cdn.dummyjson.com/product-images/43/3.jpg",
      "https://cdn.dummyjson.com/product-images/43/4.jpg",
      "https://cdn.dummyjson.com/product-images/43/thumbnail.jpg",
    ],
  },
  {
    id: "44",
    title: "Ladies Multicolored Dress",
    description:
      "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
    price: 79,
    discountPercentage: 16.88,
    rating: 4.03,
    stock: 2,
    brand: "Ghazi Fabric",
    category: "womens-dresses",
    thumbnail: "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/44/1.jpg",
      "https://cdn.dummyjson.com/product-images/44/2.jpg",
      "https://cdn.dummyjson.com/product-images/44/3.jpg",
      "https://cdn.dummyjson.com/product-images/44/4.jpg",
      "https://cdn.dummyjson.com/product-images/44/thumbnail.jpg",
    ],
  },
  {
    id: "45",
    title: "Malai Maxi Dress",
    description:
      "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
    price: 50,
    discountPercentage: 5.07,
    rating: 4.67,
    stock: 96,
    brand: "IELGY",
    category: "womens-dresses",
    thumbnail: "https://cdn.dummyjson.com/product-images/45/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/45/1.jpg",
      "https://cdn.dummyjson.com/product-images/45/2.webp",
      "https://cdn.dummyjson.com/product-images/45/3.jpg",
      "https://cdn.dummyjson.com/product-images/45/4.jpg",
      "https://cdn.dummyjson.com/product-images/45/thumbnail.jpg",
    ],
  },
  {
    id: "46",
    title: "women's shoes",
    description:
      "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
    price: 40,
    discountPercentage: 16.96,
    rating: 4.14,
    stock: 72,
    brand: "IELGY fashion",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/46/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/46/1.webp",
      "https://cdn.dummyjson.com/product-images/46/2.jpg",
      "https://cdn.dummyjson.com/product-images/46/3.jpg",
      "https://cdn.dummyjson.com/product-images/46/4.jpg",
      "https://cdn.dummyjson.com/product-images/46/thumbnail.jpg",
    ],
  },
  {
    id: "47",
    title: "Sneaker shoes",
    description:
      "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
    price: 120,
    discountPercentage: 10.37,
    rating: 4.19,
    stock: 50,
    brand: "Synthetic Leather",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg",
    images: [
      "https://cdn.dummyjson.com/product-images/47/1.jpg",
      "https://cdn.dummyjson.com/product-images/47/2.jpg",
      "https://cdn.dummyjson.com/product-images/47/3.jpg",
      "https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg",
    ],
  },
  {
    id: "48",
    title: "Women Strip Heel",
    description:
      "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
    price: 40,
    discountPercentage: 10.83,
    rating: 4.02,
    stock: 25,
    brand: "Sandals Flip Flops",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/48/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/48/1.jpg",
      "https://cdn.dummyjson.com/product-images/48/2.jpg",
      "https://cdn.dummyjson.com/product-images/48/3.jpg",
      "https://cdn.dummyjson.com/product-images/48/4.jpg",
      "https://cdn.dummyjson.com/product-images/48/thumbnail.jpg",
    ],
  },
  {
    id: "49",
    title: "Chappals & Shoe Ladies Metallic",
    description:
      "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
    price: 23,
    discountPercentage: 2.62,
    rating: 4.72,
    stock: 107,
    brand: "Maasai Sandals",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/49/1.jpg",
      "https://cdn.dummyjson.com/product-images/49/2.jpg",
      "https://cdn.dummyjson.com/product-images/49/3.webp",
      "https://cdn.dummyjson.com/product-images/49/thumbnail.jpg",
    ],
  },
  {
    id: "50",
    title: "Women Shoes",
    description:
      "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
    price: 36,
    discountPercentage: 16.87,
    rating: 4.33,
    stock: 46,
    brand: "Arrivals Genuine",
    category: "womens-shoes",
    thumbnail: "https://cdn.dummyjson.com/product-images/50/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/50/1.jpeg",
      "https://cdn.dummyjson.com/product-images/50/2.jpg",
      "https://cdn.dummyjson.com/product-images/50/3.jpg",
    ],
  },
  {
    id: "66",
    title: "Steel Analog Couple Watches",
    description: "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
    price: 35,
    discountPercentage: 3.23,
    rating: 4.79,
    stock: 24,
    brand: "Eastern Watches",
    category: "womens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/66/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/66/1.jpg",
      "https://cdn.dummyjson.com/product-images/66/2.jpg",
      "https://cdn.dummyjson.com/product-images/66/3.jpg",
      "https://cdn.dummyjson.com/product-images/66/4.JPG",
      "https://cdn.dummyjson.com/product-images/66/thumbnail.jpg",
    ],
  },
  {
    id: "67",
    title: "Fashion Magnetic Wrist Watch",
    description:
      "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
    price: 60,
    discountPercentage: 16.69,
    rating: 4.03,
    stock: 46,
    brand: "Eastern Watches",
    category: "womens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/67/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/67/1.jpg",
      "https://cdn.dummyjson.com/product-images/67/2.jpg",
      "https://cdn.dummyjson.com/product-images/67/3.jpg",
      "https://cdn.dummyjson.com/product-images/67/4.jpg",
      "https://cdn.dummyjson.com/product-images/67/thumbnail.jpg",
    ],
  },
  {
    id: "68",
    title: "Stylish Luxury Digital Watch",
    description:
      "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
    price: 57,
    discountPercentage: 9.03,
    rating: 4.55,
    stock: 77,
    brand: "Luxury Digital",
    category: "womens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/68/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/68/1.jpg",
      "https://cdn.dummyjson.com/product-images/68/2.jpg",
    ],
  },
  {
    id: "69",
    title: "Golden Watch Pearls Bracelet Watch",
    description:
      "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
    price: 47,
    discountPercentage: 17.55,
    rating: 4.77,
    stock: 89,
    brand: "Watch Pearls",
    category: "womens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/69/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/69/1.jpg",
      "https://cdn.dummyjson.com/product-images/69/2.jpg",
      "https://cdn.dummyjson.com/product-images/69/3.webp",
      "https://cdn.dummyjson.com/product-images/69/4.jpg",
      "https://cdn.dummyjson.com/product-images/69/thumbnail.jpg",
    ],
  },
  {
    id: "70",
    title: "Stainless Steel Women",
    description:
      "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
    price: 35,
    discountPercentage: 8.98,
    rating: 4.08,
    stock: 111,
    brand: "Bracelet",
    category: "womens-watches",
    thumbnail: "https://cdn.dummyjson.com/product-images/70/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/70/1.jpg",
      "https://cdn.dummyjson.com/product-images/70/2.jpg",
      "https://cdn.dummyjson.com/product-images/70/thumbnail.jpg",
    ],
  },
  {
    id: "71",
    title: "Women Shoulder Bags",
    description:
      "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
    price: 46,
    discountPercentage: 14.65,
    rating: 4.71,
    stock: 17,
    brand: "LouisWill",
    category: "womens-bags",
    thumbnail: "https://cdn.dummyjson.com/product-images/71/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/71/1.jpg",
      "https://cdn.dummyjson.com/product-images/71/2.jpg",
      "https://cdn.dummyjson.com/product-images/71/3.webp",
      "https://cdn.dummyjson.com/product-images/71/thumbnail.jpg",
    ],
  },
  {
    id: "72",
    title: "Handbag For Girls",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 23,
    discountPercentage: 17.5,
    rating: 4.91,
    stock: 27,
    brand: "LouisWill",
    category: "womens-bags",
    thumbnail: "https://cdn.dummyjson.com/product-images/72/thumbnail.webp",
    images: [
      "https://cdn.dummyjson.com/product-images/72/1.jpg",
      "https://cdn.dummyjson.com/product-images/72/2.png",
      "https://cdn.dummyjson.com/product-images/72/3.webp",
      "https://cdn.dummyjson.com/product-images/72/4.jpg",
      "https://cdn.dummyjson.com/product-images/72/thumbnail.webp",
    ],
  },
  {
    id: "73",
    title: "Fancy hand clutch",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 44,
    discountPercentage: 10.39,
    rating: 4.18,
    stock: 101,
    brand: "Bracelet",
    category: "womens-bags",
    thumbnail: "https://cdn.dummyjson.com/product-images/73/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/73/1.jpg",
      "https://cdn.dummyjson.com/product-images/73/2.webp",
      "https://cdn.dummyjson.com/product-images/73/3.jpg",
      "https://cdn.dummyjson.com/product-images/73/thumbnail.jpg",
    ],
  },
  {
    id: "74",
    title: "Leather Hand Bag",
    description:
      "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
    price: 57,
    discountPercentage: 11.19,
    rating: 4.01,
    stock: 43,
    brand: "Copenhagen Luxe",
    category: "womens-bags",
    thumbnail: "https://cdn.dummyjson.com/product-images/74/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/74/1.jpg",
      "https://cdn.dummyjson.com/product-images/74/2.jpg",
      "https://cdn.dummyjson.com/product-images/74/3.jpg",
      "https://cdn.dummyjson.com/product-images/74/4.jpg",
      "https://cdn.dummyjson.com/product-images/74/thumbnail.jpg",
    ],
  },
  {
    id: "75",
    title: "Seven Pocket Women Bag",
    description:
      "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
    price: 68,
    discountPercentage: 14.87,
    rating: 4.93,
    stock: 13,
    brand: "Steal Frame",
    category: "womens-bags",
    thumbnail: "https://cdn.dummyjson.com/product-images/75/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/75/1.jpg",
      "https://cdn.dummyjson.com/product-images/75/2.jpg",
      "https://cdn.dummyjson.com/product-images/75/3.jpg",
      "https://cdn.dummyjson.com/product-images/75/thumbnail.jpg",
    ],
  },
  {
    id: "76",
    title: "Silver Ring Set Women",
    description:
      "Jewelry Type:RingsCertificate Type:NonePlating:Silver PlatedShapeattern:noneStyle:CLASSICReligious",
    price: 70,
    discountPercentage: 13.57,
    rating: 4.61,
    stock: 51,
    brand: "Darojay",
    category: "womens-jewellery",
    thumbnail: "https://cdn.dummyjson.com/product-images/76/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/76/1.jpg",
      "https://cdn.dummyjson.com/product-images/76/2.jpg",
      "https://cdn.dummyjson.com/product-images/76/thumbnail.jpg",
    ],
  },
  {
    id: "77",
    title: "Rose Ring",
    description:
      "Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
    price: 100,
    discountPercentage: 3.22,
    rating: 4.21,
    stock: 149,
    brand: "Copenhagen Luxe",
    category: "womens-jewellery",
    thumbnail: "https://cdn.dummyjson.com/product-images/77/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/77/1.jpg",
      "https://cdn.dummyjson.com/product-images/77/2.jpg",
      "https://cdn.dummyjson.com/product-images/77/3.jpg",
      "https://cdn.dummyjson.com/product-images/77/thumbnail.jpg",
    ],
  },
  {
    id: "78",
    title: "Rhinestone Korean Style Open Rings",
    description:
      "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
    price: 30,
    discountPercentage: 8.02,
    rating: 4.69,
    stock: 9,
    brand: "Fashion Jewellery",
    category: "womens-jewellery",
    thumbnail: "https://cdn.dummyjson.com/product-images/78/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/78/thumbnail.jpg"],
  },
  {
    id: "79",
    title: "Elegant Female Pearl Earrings",
    description:
      "Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set",
    price: 30,
    discountPercentage: 12.8,
    rating: 4.74,
    stock: 16,
    brand: "Fashion Jewellery",
    category: "womens-jewellery",
    thumbnail: "https://cdn.dummyjson.com/product-images/79/thumbnail.jpg",
    images: ["https://cdn.dummyjson.com/product-images/79/1.jpg"],
  },
  {
    id: "80",
    title: "Chain Pin Tassel Earrings",
    description:
      "Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)",
    price: 45,
    discountPercentage: 17.75,
    rating: 4.59,
    stock: 9,
    brand: "Cuff Butterfly",
    category: "womens-jewellery",
    thumbnail: "https://cdn.dummyjson.com/product-images/80/thumbnail.jpg",
    images: [
      "https://cdn.dummyjson.com/product-images/80/1.jpg",
      "https://cdn.dummyjson.com/product-images/80/2.jpg",
      "https://cdn.dummyjson.com/product-images/80/3.png",
      "https://cdn.dummyjson.com/product-images/80/4.jpg",
      "https://cdn.dummyjson.com/product-images/80/thumbnail.jpg",
    ],
  },
];
